
import { auth } from "@/auth";
import TableSnapshot from "@/components/kiem-ke/table";
import { Action, SnapshotSubject } from "@/libs/enum";
import { getUserPermission } from "@/libs/getUserPermission";
import { sendRequest } from "@/utils/api";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Kiểm kê",
    description: "Generated by create next app",
};

type Params = Promise<{
    current: string;
    pageSize: string;
    room?: string;
    unit?: string;
    type?: string;
    name?: string;
    status?: string;
    year?: number
}>
const KiemKe = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser);
    if (!permission.can(Action.Read, new SnapshotSubject())) {
        redirect('/quan-tri/trang-chu')
    }

    const { pageSize = 20, current = 1, room, type, unit, name, status, year } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<ISnapshot>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/snapshot`,
        queryParams: {
            current, pageSize,
            ...(room && { room: `/${room}/i` }),
            ...(unit && { unit: `/${unit}/i` }),
            ...(type && { type: `/${type}/i` }),
            ...(name && { name: `/${name}/i` }),
            ...(status && { status: `/${status}/i` }),
            ...(year && { year }),
        },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['snapshot'] }
        }
    })

    const res1 = await sendRequest<IBackendResponse<IGetYearSnapshot>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/snapshot/available-years`,
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['snapshot'] }
        }
    })
    const res2 = await sendRequest<IBackendResponse<IModelPaginate<IRoom>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/rooms`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['rooms'] }
        }
    })
    const res3 = await sendRequest<IBackendResponse<IModelPaginate<IUnit>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/units`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['units'] }
        }
    })

    return (
        <div>
            <TableSnapshot
                snapshots={res.data?.result ?? []}
                meta={res?.data?.meta!}
                yearsArr={res1.data ?? []}
                access_token={session?.access_token ?? ''}
                rooms={res2?.data?.result ?? []}
                units={res3?.data?.result ?? []}
                user={session?.user ?? null} />
        </div>
    )
}
export default KiemKe