services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-kkts
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb+srv://hieulth_db_user:SH0hzvwMhZDNC3jx@cluster0.of7u79n.mongodb.net/kkts?authSource=admin
      - NODE_ENV=production
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: frontend-kkts
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      - NEXT_PUBLIC_BACKEND_URI=http://backend-kkts:3000
    depends_on:
      - backend
