
import { auth } from "@/auth";
import TableChungtu from "@/components/chungtu/table";
import { Action, ChungtuSubject } from "@/libs/enum";
import { getUserPermission } from "@/libs/getUserPermission";
import { sendRequest } from "@/utils/api";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Chứng từ",
    description: "Generated by create next app",
};

type Params = Promise<{ current: string; pageSize: string; noidung?: string; sotien?: number; trangthai?: string }>
const Donvi = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser);
    if (!permission.can(Action.Read, new ChungtuSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 10, current = 1, noidung, trangthai, sotien } = await searchParams
    const res = await sendRequest<IBackendResponse<IModelPaginate<IChungtu>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/chungtu`,
        queryParams: {
            current, pageSize,
            ...(sotien && { sotien }),
            ...(noidung && { noidung: `/${noidung}/i` }),
            ...(trangthai && { trangthai })
        },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['chungtu'] }
        }
    })
    return (
        <div>
            <TableChungtu
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                chungtu={res?.data?.result ?? []}
                user={session?.user ?? null} />
        </div>
    )
}
export default Donvi