import { auth } from "@/auth"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TableTbiptn from "@/components/csvc/tbiptn/table"

export const metadata: Metadata = {
    title: "Thiết bị PTN",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string; ma_tb?: string; ma_ct_csvc?: string; ten_tb?: string }>

const TbiptnPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, ma_ct_csvc, ma_tb, ten_tb } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<ITbiptn>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tbiptn`,
        queryParams: {
            current, pageSize,
            ...(ma_tb && { ma_tb: `/${ma_tb}/i` }),
            ...(ma_ct_csvc && { ma_ct_csvc }),
            ...(ten_tb && { ten_tb: `/${ten_tb}/i` })
        },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tbiptn'] } }
    })
    const resCtk = await sendRequest<IBackendResponse<IModelPaginate<ICtk>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/ctk`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['ctk'] } }
    })
    const resCountries = await sendRequest<IBackendResponse<IModelPaginate<ICountry>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/countries`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['countries'] } }
    })
    const resTinhtrangsudung = await sendRequest<IBackendResponse<IModelPaginate<ITinhtrangsudung>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tinhtrangsudung`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tinhtrangsudung'] } }
    })

    return (
        <div>
            <TableTbiptn
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                ctk={resCtk?.data?.result ?? []}
                countries={resCountries?.data?.result ?? []}
                tinhtrangsudung={resTinhtrangsudung?.data?.result ?? []}
            />
        </div>
    )
}
export default TbiptnPage
