import TinTucComponent from "@/components/public/tin.tuc";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Tin tức",
    description: "Generated by create next app",
};
const TinTuc = () => {
    return (
        <div style={{ marginTop: 32 }}>
            <p>Đang cập nhật</p>
            {/* <TinTucComponent /> */}
        </div>
    )
};

export default TinTuc;