import TinTucComponent from "@/components/public/tin-tuc/tin.tuc";
import { sendRequest } from "@/utils/api";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Tin tức",
    description: "Generated by create next app",
};
type Params = Promise<{ current: string; pageSize: string; title?: string }>
const TinTuc = async ({ searchParams }: { searchParams: Params }) => {
    const { pageSize = 3, current = 1 } = await searchParams
    const res = await sendRequest<IBackendResponse<IModelPaginate<INews>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/news`,
        queryParams: {
            current, pageSize,
            // ...(name && { name: `/${name}/i` }) 
        },
        nextOption: {
            next: { tags: ['news'] }
        }
    })
    return (
        <div style={{ marginTop: 32 }}>
            {/* chào */}
            <TinTucComponent
                meta={res?.data?.meta!}
                news={res?.data?.result ?? []}
            />
        </div>
    )
};

export default TinTuc;