import { auth } from "@/auth"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TableXth from "@/components/csvc/xth/table"

export const metadata: Metadata = {
    title: "Xưởng thực hành",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string; ma_ct_csvc?: string, phuc_vu_nganh?: string }>

const XthPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, ma_ct_csvc, phuc_vu_nganh } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IXth>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/xth`,
        queryParams: {
            current, pageSize,
            ...(phuc_vu_nganh && { phuc_vu_nganh }),
            ...(ma_ct_csvc && { ma_ct_csvc })
        },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['xth'] } }
    })
    const resCtk = await sendRequest<IBackendResponse<IModelPaginate<ICtk>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/ctk`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['ctk'] } }
    })
    const resLinhvucdaotao = await sendRequest<IBackendResponse<IModelPaginate<ILinhvucdaotao>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/linhvucdaotao`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['linhvucdaotao'] } }
    })

    return (
        <div>
            <TableXth
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                ctk={resCtk?.data?.result ?? []}
                linhvucdaotao={resLinhvucdaotao?.data?.result ?? []}
            />
        </div>
    )
}
export default XthPage
