import TaiLieuComponent from '@/components/public/tai-lieu/tai-lieu';
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Tài liệu",
    description: "Generated by create next app",
};
const TaiLieu = () => {
    return (
        <TaiLieuComponent />
    )
};

export default TaiLieu;