
import { auth } from "@/auth";
import TableNews from "@/components/tin-tuc/table";
import { Action, NewsSubject } from "@/libs/enum";
import { getUserPermission } from "@/libs/getUserPermission";
import { sendRequest } from "@/utils/api";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Tin tức",
    description: "Generated by create next app",
};

type Params = Promise<{ current: string; pageSize: string; name?: string }>
const TinTuc = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser);
    if (!permission.can(Action.Read, new NewsSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 10, current = 1, name } = await searchParams
    const res = await sendRequest<IBackendResponse<IModelPaginate<INews>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/news`,
        queryParams: {
            current, pageSize,
            // ...(name && { name: `/${name}/i` }) 
        },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['news'] }
        }
    })
    return (
        <div>
            <TableNews
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                news={res?.data?.result ?? []}
                user={session?.user ?? null} />
            {/* it is a news */}
        </div>
    )
}
export default TinTuc