import { auth } from "@/auth"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TableKtx from "@/components/csvc/ktx/table"

export const metadata: Metadata = {
    title: "Ký túc xá",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string; ma?: string; name?: string }>

const KtxPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, ma, name } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IKtx>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/ktx`,
        queryParams: { current, pageSize, ...(ma && { ma: `/${ma}/i` }), ...(name && { name: `/${name}/i` }) },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['ktx'] } }
    })

    const resSummary = await sendRequest<IBackendResponse<ISummaryCsvc[]>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/ktx/summary`,
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['ktx'] } }
    })

    return (
        <div>
            <TableKtx
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                summary={resSummary?.data ?? null}
            />
        </div>
    )
}
export default KtxPage
