import { auth } from "@/auth"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TableKtx from "@/components/csvc/ktx/table"

export const metadata: Metadata = {
    title: "Ký túc xá",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string; ma_ktx?: string }>

const KtxPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, ma_ktx } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IKtx>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/ktx`,
        queryParams: { current, pageSize, ...(ma_ktx && { ma_ktx: `/${ma_ktx}/i` }) },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['ktx'] } }
    })
    const resHinhthucsohuu = await sendRequest<IBackendResponse<IModelPaginate<IHinhthucsohuu>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/hinhthucsohuu`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['hinhthucsohuu'] } }
    })
    const resTinhtrangcsvc = await sendRequest<IBackendResponse<IModelPaginate<ITinhtrangcsvc>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tinhtrangcsvc`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tinhtrangcsvc'] } }
    })
    const resTinhtrangsudung = await sendRequest<IBackendResponse<IModelPaginate<ITinhtrangsudung>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tinhtrangsudung`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tinhtrangsudung'] } }
    })

    return (
        <div>
            <TableKtx
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                hinhthucsohuu={resHinhthucsohuu?.data?.result ?? []}
                tinhtrangcsvc={resTinhtrangcsvc?.data?.result ?? []}
                tinhtrangsudung={resTinhtrangsudung?.data?.result ?? []}
            />
        </div>
    )
}
export default KtxPage
