import { auth } from "@/auth"
import TableLythuyet from "@/components/csvc/lythuyet/table"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"

export const metadata: Metadata = {
    title: "Lý thuyết",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string, ma?: string, name?: string }>

const LythuyetPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, ma, name } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<ICsvcSubject>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/lythuyet`,
        queryParams: {
            current, pageSize, ...(ma && { ma: `/${ma}/i` }),
            ...(name && { name: `/${name}/i` })
        },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['lythuyet'] } }
    })

    const resSummary = await sendRequest<IBackendResponse<ISummaryCsvc[]>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/lythuyet/summary`,
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['lythuyet'] } }
    })

    return (
        <div>
            <TableLythuyet
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                summary={resSummary?.data ?? null}
            />
        </div>
    )
}
export default LythuyetPage
