import { auth } from "@/auth"
import TableMaytoantruong from "@/components/csvc/danhsachmaytoantruong/table"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"

export const metadata: Metadata = {
    title: "Danh sách máy toàn trường",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string; name?: string; des?: string; unit?: string; room?: string; cate?: string }>

const MaytoantruongPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, name, des, unit, room, cate } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IMaytoantruong>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/maytoantruong`,
        queryParams: {
            current, pageSize,
            ...(name && { name: `/${name}/i` }),
            ...(des && { des: `/${des}/i` }),
            ...(unit && { unit: unit }),
            ...(room && { room: room }),
            ...(cate && { cate: cate })
        },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['maytoantruong'] } }
    })
    const resUnit = await sendRequest<IBackendResponse<IModelPaginate<IUnit>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/units`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['unit'] } }
    })
    const resRoom = await sendRequest<IBackendResponse<IModelPaginate<IRoom>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/rooms`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['room'] } }
    })

    const resSummary = await sendRequest<IBackendResponse<ISummaryMaytoantruong[]>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/maytoantruong/summary`,
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['maytoantruong'] } }
    })

    return (
        <div>
            <TableMaytoantruong
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                rooms={resRoom?.data?.result ?? []}
                units={resUnit?.data?.result ?? []}
                summary={resSummary?.data ?? []}
            />
        </div>
    )
}
export default MaytoantruongPage
