import { auth } from "@/auth"
import TablePhongchucnang from "@/components/csvc/phongchucnang/table"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"

export const metadata: Metadata = {
    title: "Phòng - Chức năng",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string, ma?: string, name?: string, type?: string }>

const PhongchucnangPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, ma, name, type } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IPhongchucnang>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/phongchucnang`,
        queryParams: {
            current, pageSize, ...(ma && { ma: `/${ma}/i` }),
            ...(name && { name: `/${name}/i` }),
            ...(type && { type: type })
        },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['phongchucnang'] } }
    })

    const resSummary = await sendRequest<IBackendResponse<any[]>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/phongchucnang/summary`,
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['phongchucnang'] } }
    })

    const resType = await sendRequest<IBackendResponse<IModelPaginate<ILoaiphong>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/loaiphong`,
        queryParams: { current: 1, pageSize: 1000 },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['loaiphong'] }
        }
    })

    return (
        <div>
            <TablePhongchucnang
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                summary={resSummary?.data ?? null}
                type={resType?.data?.result ?? []}
            />
        </div>
    )
}
export default PhongchucnangPage
