
import { auth } from "@/auth";
import TableNccs from "@/components/ncc/table";
import { Action, ChungtuSubject } from "@/libs/enum";
import { getUserPermission } from "@/libs/getUserPermission";
import { sendRequest } from "@/utils/api";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Nhà cung cấp",
    description: "Generated by create next app",
};

type Params = Promise<{ current: string; pageSize: string; name?: string }>
const Ncc = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser);
    if (!permission.can(Action.Read, new ChungtuSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 10, current = 1, name } = await searchParams
    const res = await sendRequest<IBackendResponse<IModelPaginate<IUnit>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/ncc`,
        queryParams: { current, pageSize, ...(name && { name: `/${name}/i` }) },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['ncc'] }
        }
    })
    return (
        <div>
            <TableNccs
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                ncc={res?.data?.result ?? []}
                user={session?.user ?? null} />
        </div>
    )
}
export default Ncc