import { auth } from "@/auth"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TablePtn from "@/components/csvc/ptn/table"

export const metadata: Metadata = {
    title: "Phòng thí nghiệm",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string }>

const PtnPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1 } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IPtn>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/ptn`,
        queryParams: { current, pageSize },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['ptn'] } }
    })
    const resCtk = await sendRequest<IBackendResponse<IModelPaginate<ICtk>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/ctk`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['ctk'] } }
    })
    const resLoaiptn = await sendRequest<IBackendResponse<IModelPaginate<ILoaiptn>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/loaiptn`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['loaiptn'] } }
    })
    const resLinhvucdaotao = await sendRequest<IBackendResponse<IModelPaginate<ILinhvucdaotao>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/linhvucdaotao`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['linhvucdaotao'] } }
    })

    return (
        <div>
            <TablePtn
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                ctk={resCtk?.data?.result ?? []}
                loaiptn={resLoaiptn?.data?.result ?? []}
                linhvucdaotao={resLinhvucdaotao?.data?.result ?? []}
            />
        </div>
    )
}
export default PtnPage
