import { auth } from "@/auth"
import { Action, DanhmucSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TableXaphuong from "@/components/csvc/danh-muc/xa-phuong/table"

export const metadata: Metadata = {
    title: "Xã/Phường",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string; name?: string; tinhthanhpho?: string }>

const XaPhuongPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new DanhmucSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, name, tinhthanhpho } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IXaphuong>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/xaphuong`,
        queryParams: { current, pageSize, ...(name && { name: `/${name}/i` }), ...(tinhthanhpho && { tinhthanhpho }) },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['xaphuong'] } }
    })
    const resTinhthanhpho = await sendRequest<IBackendResponse<IModelPaginate<ITinhthanhpho>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tinhthanhpho`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tinhthanhpho'] } }
    })

    return (
        <div>
            <TableXaphuong
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                tinhthanhpho={resTinhthanhpho?.data?.result ?? []}
            />
        </div>
    )
}
export default XaPhuongPage
