import { auth } from "@/auth"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TableToanha from "@/components/csvc/toa-nha/table"

export const metadata: Metadata = {
    title: "Tòa nhà",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string, ma_toanha?: string, ten_toanha?: string, place?: string }>

const ToaNhaPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, ma_toanha, ten_toanha, place } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IToanha>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/toanha`,
        queryParams: {
            current, pageSize, ...(ma_toanha && { ma_toanha: `/${ma_toanha}/i` }),
            ...(ten_toanha && { ten_toanha: `/${ten_toanha}/i` }),
            ...(place && { place: +place })
        },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['toanha'] } }
    })

    const resSummary = await sendRequest<IBackendResponse<ISummaryToanha[]>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/toanha/summary`,
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['toanha'] } }
    })

    return (
        <div>
            <TableToanha
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                summary={resSummary?.data ?? null}
            />
        </div>
    )
}
export default ToaNhaPage
