import { auth } from "@/auth"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TableThuvien from "@/components/csvc/thu-vien/table"

export const metadata: Metadata = {
    title: "Thư viện",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string; ma_thuvien?: string, name?: string }>

const ThuVienPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, ma_thuvien, name } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IThuvien>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/thuvien`,
        queryParams: {
            current, pageSize,
            ...(ma_thuvien && { ma_thuvien: `/${ma_thuvien}/i` }),
            ...(name && { name: `/${name}/i` }),
        },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['thuvien'] } }
    })
    const resTinhtrangcsvc = await sendRequest<IBackendResponse<IModelPaginate<ITinhtrangcsvc>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tinhtrangcsvc`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tinhtrangcsvc'] } }
    })
    const resHinhthucsohuu = await sendRequest<IBackendResponse<IModelPaginate<IHinhthucsohuu>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/hinhthucsohuu`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['hinhthucsohuu'] } }
    })
    const resTinhtrangsudung = await sendRequest<IBackendResponse<IModelPaginate<ITinhtrangsudung>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tinhtrangsudung`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tinhtrangsudung'] } }
    })

    return (
        <div>
            <TableThuvien
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                tinhtrangcsvc={resTinhtrangcsvc?.data?.result ?? []}
                hinhthucsohuu={resHinhthucsohuu?.data?.result ?? []}
                tinhtrangsudung={resTinhtrangsudung?.data?.result ?? []}
            />
        </div>
    )
}
export default ThuVienPage
