import VaiTroComponent from "@/components/public/vai-tro/vai.tro";
import { Metadata } from "next";


export const metadata: Metadata = {
    title: "Chức năng - Nhiệm vụ",
    description: "Generated by create next app",
};

const VaiTro = () => {
    return (
        <VaiTroComponent />
    )
};

export default VaiTro;