import NewsDetail from "@/components/public/tin-tuc/news.detail"
import { sendRequest } from "@/utils/api"
import dayjs from "dayjs"
import type { Metadata, ResolvingMetadata } from 'next'


type Props = {
    params: Promise<{ slug: string }>
    searchParams: Promise<{ [key: string]: string | string[] | undefined }>
}

export async function generateMetadata(
    { params, searchParams }: Props,
    parent: ResolvingMetadata
): Promise<Metadata> {
    const slug = (await params).slug

    // fetch post information
    const post = await sendRequest<IBackendResponse<INews>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/news/${slug}`,
        nextOption: {
            next: { tags: ['news'] }
        }
    })

    return {
        title: post.data?.title,
        description: "Generated by create next app",
    }
}

export default async function Page({
    params,
}: {
    params: Promise<{ slug: string }>
}) {
    const { slug } = await params
    const res = await sendRequest<IBackendResponse<INews>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/news/${slug}`,
        nextOption: {
            next: { tags: ['news'] }
        }
    })
    return (
        <div style={{ marginTop: 32 }}>
            <span style={{ color: '#343030' }}>Ngày đăng: {dayjs(res.data?.postedAt).add(1, 'day').format('DD/MM/YYYY')}</span>
            <h2 style={{ marginTop: 8, color: '#1b4d85' }}>{res.data?.title}</h2>
            <NewsDetail content={res.data?.content} />
        </div>
    )
}