import { auth } from "@/auth"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TablePhgdht from "@/components/csvc/phgdht/table"

export const metadata: Metadata = {
    title: "Phòng học / Giảng đường / Hội trường",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string }>

const PhgdhtPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1 } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IPhgdht>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/phgdht`,
        queryParams: { current, pageSize },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['phgdht'] } }
    })
    const resHinhthucsohuu = await sendRequest<IBackendResponse<IModelPaginate<IHinhthucsohuu>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/hinhthucsohuu`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['hinhthucsohuu'] } }
    })
    const resTinhtrangcsvc = await sendRequest<IBackendResponse<IModelPaginate<ITinhtrangcsvc>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tinhtrangcsvc`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tinhtrangcsvc'] } }
    })
    const resPhanloai = await sendRequest<IBackendResponse<IModelPaginate<IPhanloai>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/phanloai`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['phanloai'] } }
    })
    const resLoaiphonghoc = await sendRequest<IBackendResponse<IModelPaginate<ILoaiphonghoc>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/loaiphonghoc`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['loaiphonghoc'] } }
    })
    const resLoaidean = await sendRequest<IBackendResponse<IModelPaginate<ILoaidean>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/loaidean`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['loaidean'] } }
    })
    const resTinhtrangsudung = await sendRequest<IBackendResponse<IModelPaginate<ITinhtrangsudung>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tinhtrangsudung`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tinhtrangsudung'] } }
    })

    return (
        <div>
            <TablePhgdht
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                hinhthucsohuu={resHinhthucsohuu?.data?.result ?? []}
                tinhtrangcsvc={resTinhtrangcsvc?.data?.result ?? []}
                phanloai={resPhanloai?.data?.result ?? []}
                loaiphonghoc={resLoaiphonghoc?.data?.result ?? []}
                loaidean={resLoaidean?.data?.result ?? []}
                tinhtrangsudung={resTinhtrangsudung?.data?.result ?? []}
            />
        </div>
    )
}
export default PhgdhtPage
