import { auth } from "@/auth";
import TableUsers from "@/components/tai-khoan/table";
import { Action, UserSubject } from "@/libs/enum";
import { getUserPermission } from "@/libs/getUserPermission";
import { sendRequest } from "@/utils/api";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Tài khoản",
    description: "Generated by create next app",
};

type Params = Promise<{ current: string; pageSize: string }>
const Taikhoan = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser);
    if (!permission.can(Action.Read, new UserSubject())) {
        redirect('/quan-tri/trang-chu')
    }

    const { pageSize = 10, current = 1 } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IUser>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/users`,
        queryParams: { current, pageSize },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['users'] }
        }
    })
    const res1 = await sendRequest<IBackendResponse<IModelPaginate<IUnit>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/units`,
        queryParams: { current: 1, pageSize: 100 },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['units'] }
        }
    })
    return (
        <div>
            <TableUsers
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                users={res?.data?.result ?? []}
                units={res1?.data?.result ?? []}
                user={session?.user ?? null} />
        </div>
    )
}
export default Taikhoan