
import { auth } from "@/auth";
import TableDevices from "@/components/thiet-bi/table";
import { Action, DeviceSubject } from "@/libs/enum";
import { getUserPermission } from "@/libs/getUserPermission";
import { sendRequest } from "@/utils/api";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Thiết bị",
    description: "Generated by create next app",
};

type Params = Promise<{
    current: string;
    pageSize: string;
    currentRoom?: string;
    unit?: string;
    type?: string;
    name?: string;
}>
const Thietbi = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser);
    if (!permission.can(Action.Read, new DeviceSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 10, current = 1, currentRoom, type, unit, name } = await searchParams
    const res = await sendRequest<IBackendResponse<IModelPaginate<IDevice>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/devices`,
        queryParams: {
            current, pageSize,
            ...(currentRoom && { currentRoom }),
            ...(unit && { unit }),
            ...(type && { type }),
            ...(name && { name: `/${name}/i` }),
        },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['devices'] }
        }
    })
    const res1 = await sendRequest<IBackendResponse<IModelPaginate<IRoom>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/rooms`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['rooms'] }
        }
    })
    const res2 = await sendRequest<IBackendResponse<IModelPaginate<IUnit>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/units`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['units'] }
        }
    })
    return (
        <div>
            <TableDevices
                devices={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                rooms={res1?.data?.result ?? []}
                units={res2?.data?.result ?? []}
                user={session?.user ?? null} />
        </div>
    )
}
export default Thietbi