
import { auth } from "@/auth";
import TableRequests from "@/components/de-nghi/table";
import { Action, RequestSubject } from "@/libs/enum";
import { getUserPermission } from "@/libs/getUserPermission";
import { sendRequest } from "@/utils/api";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Đề nghị",
    description: "Generated by create next app",
};

type Params = Promise<{ current: string; pageSize: string; unit?: string; name?: string, createdBy?: string, status?: string, type?: string }>
const Denghi = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser);
    if (!permission.can(Action.Read, new RequestSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, name, unit, createdBy, status, type } = await searchParams
    const res = await sendRequest<IBackendResponse<IModelPaginate<IRequestModule>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/requests`,
        queryParams: {
            current, pageSize,
            ...(unit && { unit }),
            ...(status && { status }),
            ...(type && { type }),
            ...(name && { name: `/${name}/i` }),
            ...(createdBy && { createdBy: `/${createdBy}/i` })
        },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['requests'] }
        }
    })
    const res2 = await sendRequest<IBackendResponse<IModelPaginate<IUnit>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/units`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['units'] }
        }
    })
    return (
        <div>
            <TableRequests
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                requests={res?.data?.result ?? []}
                units={res2?.data?.result ?? []}
                user={session?.user ?? null} />
        </div>
    )
}
export default Denghi