import GioithieuComponent from '@/components/public/gioi-thieu/gioi.thieu';
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "Giới thiệu",
    description: "Generated by create next app",
};

const MyHome = () => {
    return (
        <GioithieuComponent />
    )
};

export default MyHome;