import { auth } from "@/auth"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TableDatdai from "@/components/csvc/dat-dai/table"

export const metadata: Metadata = {
    title: "Đất đai",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string }>

const DatDaiPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1 } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IDatdai>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/datdai`,
        queryParams: { current, pageSize },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['datdai'] } }
    })
    const resHinhthucsudung = await sendRequest<IBackendResponse<IModelPaginate<IHinhthucsudung>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/hinhthucsudung`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['hinhthucsudung'] } }
    })
    const resMucdichsudungdat = await sendRequest<IBackendResponse<IModelPaginate<IMucdichsudungdat>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/mucdichsudungdat`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['mucdichsudungdat'] } }
    })
    const resTinhtrangsudung = await sendRequest<IBackendResponse<IModelPaginate<ITinhtrangsudung>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tinhtrangsudung`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tinhtrangsudung'] } }
    })
    const resTinhthanhpho = await sendRequest<IBackendResponse<IModelPaginate<ITinhthanhpho>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tinhthanhpho`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tinhthanhpho'] } }
    })
    const resXaphuong = await sendRequest<IBackendResponse<IModelPaginate<IXaphuong>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/xaphuong`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['xaphuong'] } }
    })

    return (
        <div>
            <TableDatdai
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                hinhthucsudung={resHinhthucsudung?.data?.result ?? []}
                mucdichsudungdat={resMucdichsudungdat?.data?.result ?? []}
                tinhtrangsudung={resTinhtrangsudung?.data?.result ?? []}
                tinhthanhpho={resTinhthanhpho?.data?.result ?? []}
                xaphuong={resXaphuong?.data?.result ?? []}
            />
        </div>
    )
}
export default DatDaiPage
