import { auth } from "@/auth"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TableDatdai from "@/components/csvc/dat-dai/table"

export const metadata: Metadata = {
    title: "Đất đai",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string, ma_giay_cnqsh?: string }>

const DatDaiPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, ma_giay_cnqsh } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<IDatdai>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/datdai`,
        queryParams: { current, pageSize, ...(ma_giay_cnqsh && { ma_giay_cnqsh: `/${ma_giay_cnqsh}/i` }) },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['datdai'] } }
    })
    const resSummary = await sendRequest<IBackendResponse<ISummary>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/datdai/summary`,
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['datdai'] } }
    })

    return (
        <div>
            <TableDatdai
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                summary={resSummary?.data ?? { totalArea: 0, revokedArea: 0 }}
            />
        </div>
    )
}
export default DatDaiPage
