import { auth } from "@/auth"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TableCtk from "@/components/csvc/ctk/table"

export const metadata: Metadata = {
    title: "Công trình CSVC",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string, ma_ct?: string }>

const CtkPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, ma_ct } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<ICtk>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/ctk`,
        queryParams: { current, pageSize, ...(ma_ct && { ma_ct: `/${ma_ct}/i` }) },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['ctk'] } }
    })
    const resLoaicongtrinhcsvc = await sendRequest<IBackendResponse<IModelPaginate<ILoaicongtrinhcsvc>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/loaicongtrinhcsvc`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['loaicongtrinhcsvc'] } }
    })
    const resMucdichsudungcsvc = await sendRequest<IBackendResponse<IModelPaginate<IMucdichsudungcsvc>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/mucdichsudungcsvc`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['mucdichsudungcsvc'] } }
    })
    const resTinhtrangcsvc = await sendRequest<IBackendResponse<IModelPaginate<ITinhtrangcsvc>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tinhtrangcsvc`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tinhtrangcsvc'] } }
    })
    const resHinhthucsohuu = await sendRequest<IBackendResponse<IModelPaginate<IHinhthucsohuu>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/hinhthucsohuu`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['hinhthucsohuu'] } }
    })
    const resLuachon = await sendRequest<IBackendResponse<IModelPaginate<ILuachon>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/luachon`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['luachon'] } }
    })
    const resTinhtrangsudung = await sendRequest<IBackendResponse<IModelPaginate<ITinhtrangsudung>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tinhtrangsudung`,
        queryParams: { current: 1, pageSize: 100000 },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tinhtrangsudung'] } }
    })

    return (
        <div>
            <TableCtk
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                loaicongtrinhcsvc={resLoaicongtrinhcsvc?.data?.result ?? []}
                mucdichsudungcsvc={resMucdichsudungcsvc?.data?.result ?? []}
                tinhtrangcsvc={resTinhtrangcsvc?.data?.result ?? []}
                hinhthucsohuu={resHinhthucsohuu?.data?.result ?? []}
                luachon={resLuachon?.data?.result ?? []}
                tinhtrangsudung={resTinhtrangsudung?.data?.result ?? []}
            />
        </div>
    )
}
export default CtkPage
