import { auth } from "@/auth"
import { Action, DanhmucSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"
import TableLoaiphonghoc from "@/components/csvc/danh-muc/loai-phong-hoc/table"

export const metadata: Metadata = {
    title: "Loại phòng học",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string, name: string }>

const LoaiPhongHocPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new DanhmucSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, name } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<ILoaiphonghoc>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/loaiphonghoc`,
        queryParams: { current, pageSize, ...(name && { name: `/${name}/i` }) },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['loaiphonghoc'] } }
    })

    return (
        <div>
            <TableLoaiphonghoc
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
            />
        </div>
    )
}
export default LoaiPhongHocPage
