import { auth } from "@/auth";
import Dashboard from "@/components/dashboard/dashboard";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Trang chủ",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth()
    return (
        <Dashboard
            email={session?.user?.email ?? ''}
            access_token={session?.access_token ?? ''}
            user={session?.user ?? {} as IUser}
        >{children}</Dashboard>
    );
}
