
import { auth } from "@/auth";
import TableRooms from "@/components/phong-kho/table";
import { Action, RoomSubject } from "@/libs/enum";
import { getUserPermission } from "@/libs/getUserPermission";
import { sendRequest } from "@/utils/api";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Phòng kho",
    description: "Generated by create next app",
};

type Params = Promise<{ current: string; pageSize: string, unit?: string; name?: string }>
const PhongKho = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser);
    if (!permission.can(Action.Read, new RoomSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 20, current = 1, unit, name } = await searchParams
    const res = await sendRequest<IBackendResponse<IModelPaginate<IRoom>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/rooms`,
        queryParams: {
            current, pageSize,
            ...(unit && { currentUnit: unit }),
            ...(name && { name: `/${name}/i` })
        },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['rooms'] }
        }
    })
    const res1 = await sendRequest<IBackendResponse<IModelPaginate<IUnit>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/units`,
        queryParams: { current: 1, pageSize: 1000 },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['units'] }
        }
    })
    return (
        <div>
            <TableRooms
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                rooms={res?.data?.result ?? []}
                units={res1?.data?.result ?? []}
                user={session?.user ?? null} />
        </div>
    )
}
export default PhongKho