import { auth } from "@/auth"
import TableTBTren500tr from "@/components/csvc/tbtren500tr/table"
import { Action, CsvcSubject } from "@/libs/enum"
import { getUserPermission } from "@/libs/getUserPermission"
import { sendRequest } from "@/utils/api"
import { Metadata } from "next"
import { redirect } from "next/navigation"

export const metadata: Metadata = {
    title: "Thiết bị trên 500 triệu",
    description: "Generated by create next app",
}

type Params = Promise<{ current: string; pageSize: string, code?: string, name?: string, unit?: string }>

const Thietbitren500trPage = async ({ searchParams }: { searchParams: Params }) => {
    const session = await auth()
    const permission = getUserPermission(session?.user ?? {} as IUser)
    if (!permission.can(Action.Read, new CsvcSubject())) {
        redirect('/quan-tri/trang-chu')
    }
    const { pageSize = 50, current = 1, code, name, unit } = await searchParams

    const res = await sendRequest<IBackendResponse<IModelPaginate<ITBTren500tr>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tbtren500tr`,
        queryParams: {
            current, pageSize, ...(code && { code: `/${code}/i` }),
            ...(name && { name: `/${name}/i` }),
            ...(unit && { unit: unit })
        },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tbtren500tr'] } }
    })

    const res1 = await sendRequest<IBackendResponse<IModelPaginate<IUnit>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/units`,
        queryParams: { current: 1, pageSize: 1000 },
        headers: {
            Authorization: `Bearer ${session?.access_token}`,
        },
        nextOption: {
            next: { tags: ['units'] }
        }
    })

    const res2 = await sendRequest<IBackendResponse<IModelPaginate<ITBTren500tr>>>({
        url: `${process.env.NEXT_PUBLIC_BACKEND_URI}/tbtren500tr/getall`,
        queryParams: {
            current: 1, pageSize: 1000
        },
        headers: { Authorization: `Bearer ${session?.access_token}` },
        nextOption: { next: { tags: ['tbtren500tr'] } }
    })

    return (
        <div>

            <TableTBTren500tr
                data={res?.data?.result ?? []}
                access_token={session?.access_token ?? ''}
                meta={res?.data?.meta!}
                user={session?.user ?? null}
                // summary={resSummary?.data ?? null}
                units={res1?.data?.result ?? []}
                availableChildren={res2?.data?.result ?? []}
            />
        </div>
    )
}
export default Thietbitren500trPage
